version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    # Dependabot defaults to 5 open pull requests at a time
    open-pull-requests-limit: 100
    # ignore versions already covered by a range
    # e.g: ^1.2.3 -> 1.2.4, would be ignored
    versioning-strategy: increase-if-necessary

    # Group together PRs of interdependant packages
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/util-dynamodb'
      remix-run:
        patterns:
          - '@remix-run/node'
          - '@remix-run/react'
          - '@remix-run/testing'
          - '@remix-run/server-runtime'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/client'
      jest-core:
        patterns:
          - 'jest'
          - 'jest-circus'
      react:
        patterns:
          - 'react'
          - 'react-dom'
