name: shopify-api-js

type: node

up:
  - node:
      version: v20.10.0
      package_manager: pnpm@10.16.1
      packages:
        - .
env:
  NODE_ENV: "development"

commands:
  server:
    run: pnpm dev
