name: shopify-api-js

type: node

up:
  - node:
      version: v18.19.0
      package_manager: pnpm@9.7.1
      packages:
        - .
env:
  NODE_ENV: 'development'

commands:
  server:
    run: pnpm dev
  test:
    run: pnpm test
